/*
 * OAuthTestApi.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */
using System;

namespace OAuthTestApi.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "http://vcs-oauth-test-endpoint.azurewebsites.net:80";

        //The OAuth token to be set before API calls
        //TODO: Replace the OAuthToken with an appropriate value
        public static string OAuthToken = "TODO: Replace";

        //The OAuth token secret to be set before API calls
        //TODO: Replace the OAuthTokenSecret with an appropriate value
        public static string OAuthTokenSecret = "TODO: Replace";

        //The OAuth client id to be set before API calls
        //TODO: Replace the OAuthClientId with an appropriate value
        public static string OAuthClientId = "TODO: Replace";

        //The OAuth client secret to be set before API calls
        //TODO: Replace the OAuthClientSecret with an appropriate value
        public static string OAuthClientSecret = "TODO: Replace";

    }
}