/*
 * OAuthTestApi.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */
using System;
using OAuthTestApi.PCL.Controllers;

namespace OAuthTestApi.PCL
{
    public partial class OAuthTestApiClient
    {

        /// <summary>
        /// Singleton access to Dogs controller
        /// </summary>
        public DogsController Dogs
        {
            get
            {
                return DogsController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public OAuthTestApiClient(string oAuthToken, string oAuthTokenSecret, string oAuthClientId, string oAuthClientSecret)
        {
            Configuration.OAuthToken = oAuthToken;
            Configuration.OAuthTokenSecret = oAuthTokenSecret;
            Configuration.OAuthClientId = oAuthClientId;
            Configuration.OAuthClientSecret = oAuthClientSecret;
        }
    }
}